web/router.ex
defmodule UeberauthExample.Router do
  @moduledoc false

  use UeberauthExample.Web, :router
  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", UeberauthExample do
    pipe_through [:browser]

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  scope "/", UeberauthExample do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end
end

lib/ueberauth_example/endpoint.ex
defmodule UeberauthExample.Endpoint do
  @moduledoc false

  use Phoenix.Endpoint, otp_app: :ueberauth_example

  socket "/socket", UeberauthExample.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :ueberauth_example, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_ueberauth_example_key",
    signing_salt: "pJYawTy2"

  plug UeberauthExample.Router
end

lib/ueberauth_example/repo.ex
defmodule UeberauthExample.Repo do
  @moduledoc false

  use Ecto.Repo, otp_app: :ueberauth_example
end

web/models/user_from_auth.ex
defmodule UserFromAuth do
  @moduledoc """
  Retrieve the user information from an auth request
  """

  alias Ueberauth.Auth

  def find_or_create(%Auth{provider: :identity} = auth) do
    case validate_pass(auth.credentials) do
      :ok ->
        {:ok, basic_info(auth)}
      {:error, reason} -> {:error, reason}
    end
  end

  def find_or_create(%Auth{} = auth) do
    {:ok, basic_info(auth)}
  end

  defp basic_info(auth) do
    %{id: auth.uid, name: name_from_auth(auth), avatar: auth.info.image}
  end

  defp name_from_auth(auth) do
    if auth.info.name do
      auth.info.name
    else
      name = [auth.info.first_name, auth.info.last_name]
      |> Enum.filter(&(&1 != nil and &1 != ""))

      cond do
        length(name) == 0 -> auth.info.nickname
        true -> Enum.join(name, " ")
      end
    end
  end

  defp validate_pass(%{other: %{password: ""}}) do
    {:error, "Password required"}
  end
  defp validate_pass(%{other: %{password: pw, password_confirmation: pw}}) do
    :ok
  end
  defp validate_pass(%{other: %{password: _}}) do
    {:error, "Passwords do not match"}
  end
  defp validate_pass(_), do: {:error, "Password Required"}
end

web/controllers/auth_controller.ex
defmodule UeberauthExample.AuthController do
  @moduledoc """
  Auth controller responsible for handling Ueberauth responses
  """

  use UeberauthExample.Web, :controller
  plug Ueberauth

  alias Ueberauth.Strategy.Helpers

  def request(conn, _params) do
    render(conn, "request.html", callback_url: Helpers.callback_url(conn))
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "You have been logged out!")
    |> configure_session(drop: true)
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Failed to authenticate.")
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    case UserFromAuth.find_or_create(auth) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Successfully authenticated.")
        |> put_session(:current_user, user)
        |> redirect(to: "/")
      {:error, reason} ->
        conn
        |> put_flash(:error, reason)
        |> redirect(to: "/")
    end
  end
end

web/controllers/page_controller.ex
defmodule UeberauthExample.PageController do
  @moduledoc """
  Static page controller
  """

  use UeberauthExample.Web, :controller

  def index(conn, _params) do
    render conn, "index.html", current_user: get_session(conn, :current_user)
  end
end

web/views/auth_view.ex
defmodule UeberauthExample.AuthView do
  @moduledoc false

  use UeberauthExample.Web, :view
end

web/views/error_view.ex
defmodule UeberauthExample.ErrorView do
  @moduledoc false

  use UeberauthExample.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule UeberauthExample.LayoutView do
  @moduledoc false

  use UeberauthExample.Web, :view
end

web/views/page_view.ex
defmodule UeberauthExample.PageView do
  @moduledoc false

  use UeberauthExample.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Überauth Example</title>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li>
            <a href="https://github.com/ueberauth/ueberauth_example">
              <i class="fa fa-github"></i>
              View on GitHub
            </a>
          </li>
        </ul>
        <span class="logo"></span>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Überauth + Phoenix Example</h2>
  <p class="lead">
  This is an application to show an example of how to wire up
  <a href="https://github.com/ueberauth/ueberauth">Überauth</a> with
  <a href="https://github.com/phoenixframework/phoenix">Phoenix</a>.
  </p>

  <%= if @current_user do %>
    <h2>Welcome, <%= @current_user.name %>!</h2>
    <img src="<%= @current_user.avatar %>" class="img-circle"/>
    <%= link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-danger" %>
    <br>
  <% else %>
    <a class="btn btn-primary btn-lg" href="/auth/github">
      <i class="fa fa-github"></i>
      Sign in with GitHub
    </a>

    <a class="btn btn-primary btn-lg" href="/auth/facebook">
      <i class="fa fa-facebook"></i>
      Sign in with Facebook
    </a>

    <a class="btn btn-primary btn-lg" href="/auth/google">
      <i class="fa fa-google"></i>
      Sign in with Google
    </a>

    <a class="btn btn-primary btn-lg" href="/auth/slack">
      <i class="fa fa-slack"></i>
      Sign in with Slack
    </a>

    <a class="btn btn-primary btn-lg" href="/auth/twitter">
      <i class="fa fa-twitter"></i>
      Sign in with Twitter
    </a>

    <a class="btn btn-primary btn-lg" href="/auth/identity">
      <i class="fa fa-user"></i>
      Sign in with Username/Password
    </a>
  <% end %>
</div>